import { Theme } from '@/types';

export const careerThemes: Theme[] = [
  // Medical & Healthcare
  { id: 'doctor', title: 'Medical Doctor 🩺', emoji: '🩺', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme52/400/500', prompt: 'Transform the person in the image into a professional Medical Doctor. Attire: White coat with stethoscope around neck. Setting: Modern hospital ward with medical equipment. Props: Clipboard with patient notes, stethoscope. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'surgeon', title: 'Surgeon 🔪', emoji: '🔪', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme53/400/500', prompt: 'Transform the person into a professional Surgeon. Attire: Surgical scrubs with mask pulled down, surgical cap. Setting: Bright operating theatre with surgical lights. Props: Surgical gloves, medical instruments. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'nurse', title: 'Nurse 💉', emoji: '💉', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme54/400/500', prompt: 'Transform the person into a professional Nurse. Attire: Nursing uniform or scrubs with nurse cap or ID badge. Setting: Hospital ward with patient beds. Props: Syringe, medical chart. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'dentist', title: 'Dentist 🦷', emoji: '🦷', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme55/400/500', prompt: 'Transform the person into a professional Dentist. Attire: White dental coat with mask and gloves. Setting: Modern dental clinic with dental chair. Props: Dental instruments, overhead light. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'pharmacist', title: 'Pharmacist 💊', emoji: '💊', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme56/400/500', prompt: 'Transform the person into a professional Pharmacist. Attire: White lab coat with name badge. Setting: Pharmacy with shelves of medicines. Props: Prescription bottles, computer terminal. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'paramedic', title: 'Paramedic 🚑', emoji: '🚑', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme57/400/500', prompt: 'Transform the person into a professional Paramedic. Attire: EMT uniform with high-vis vest. Setting: Ambulance background or emergency scene. Props: Medical bag, defibrillator. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'psychiatrist', title: 'Psychiatrist 🧠', emoji: '🧠', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme58/400/500', prompt: 'Transform the person into a professional Psychiatrist. Attire: Formal business attire. Setting: Comfortable consultation room with couch. Props: Notepad, pen, diploma on wall. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'physiotherapist', title: 'Physiotherapist 🏋️', emoji: '🏋️', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme59/400/500', prompt: 'Transform the person into a professional Physiotherapist. Attire: Sports or clinical attire. Setting: Physiotherapy room with exercise equipment. Props: Resistance bands, treatment table. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'radiologist', title: 'Radiologist 🩻', emoji: '🩻', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme60/400/500', prompt: 'Transform the person into a professional Radiologist. Attire: White lab coat. Setting: Radiology room with X-ray lightboard displaying scans. Props: X-ray images, pointing device. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'veterinarian', title: 'Veterinarian 🐾', emoji: '🐾', type: 'career', category: 'Medical & Healthcare', bgImage: 'https://picsum.photos/seed/theme61/400/500', prompt: 'Transform the person into a professional Veterinarian. Attire: Veterinary coat with stethoscope. Setting: Animal clinic examination room. Props: Small animal on examination table. Maintain the person\'s facial features and likeness accurately.' },

  // Engineering & Technology
  { id: 'software_engineer', title: 'Software Engineer 💻', emoji: '💻', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme62/400/500', prompt: 'Transform the person into a professional Software Engineer. Attire: Smart casual (hoodie or button-down). Setting: Modern tech office with dual monitors showing code. Props: Laptop, coffee mug. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'civil_engineer', title: 'Civil Engineer 🏗️', emoji: '🏗️', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme63/400/500', prompt: 'Transform the person into a professional Civil Engineer. Attire: Hard hat, high-visibility vest, safety boots. Setting: Construction site with building structure. Props: Blueprint roll, measuring tools. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'mechanical_engineer', title: 'Mechanical Engineer ⚙️', emoji: '⚙️', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme64/400/500', prompt: 'Transform the person into a professional Mechanical Engineer. Attire: Engineering overalls or work clothes. Setting: Workshop with machinery and tools. Props: Wrench, technical drawings. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'electrical_engineer', title: 'Electrical Engineer ⚡', emoji: '⚡', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme65/400/500', prompt: 'Transform the person into a professional Electrical Engineer. Attire: Safety gear with hard hat. Setting: Electrical control room with panels. Props: Multimeter, circuit diagrams. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'aerospace_engineer', title: 'Aerospace Engineer 🛸', emoji: '🛸', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme66/400/500', prompt: 'Transform the person into a professional Aerospace Engineer. Attire: Lab coat or technical uniform. Setting: Aircraft hangar with a jet plane. Props: Technical tablet, airplane model. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'data_scientist', title: 'Data Scientist 📊', emoji: '📊', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme67/400/500', prompt: 'Transform the person into a professional Data Scientist. Attire: Business casual. Setting: Modern office with multiple screens showing analytics dashboards. Props: Laptop with data visualizations. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'cybersecurity', title: 'Cybersecurity Expert 🔐', emoji: '🔐', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme68/400/500', prompt: 'Transform the person into a professional Cybersecurity Expert. Attire: Dark hoodie or formal business wear. Setting: Dimly lit server room with multiple monitors showing code. Props: Keyboard, security alert screens. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'robotics_engineer', title: 'Robotics Engineer 🤖', emoji: '🤖', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme69/400/500', prompt: 'Transform the person into a professional Robotics Engineer. Attire: Lab coat with safety glasses. Setting: High-tech robotics laboratory. Props: Robot arm, tablet with schematics. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'network_engineer', title: 'Network Engineer 🌐', emoji: '🌐', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme70/400/500', prompt: 'Transform the person into a professional Network Engineer. Attire: Business casual. Setting: Data centre with server racks and cables. Props: Laptop, network cables. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'ai_engineer', title: 'AI / ML Engineer 🧠', emoji: '🧠', type: 'career', category: 'Engineering & Technology', bgImage: 'https://picsum.photos/seed/theme71/400/500', prompt: 'Transform the person into a professional AI/ML Engineer. Attire: Smart casual in modern tech office. Setting: Multiple screens showing neural network visualizations and code. Props: Laptop with AI model interface. Maintain the person\'s facial features and likeness accurately.' },

  // Law & Government
  { id: 'lawyer', title: 'Lawyer / Advocate ⚖️', emoji: '⚖️', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme72/400/500', prompt: 'Transform the person into a professional Lawyer. Attire: Formal black suit or legal gown with tie. Setting: Courtroom or law library with law books. Props: Legal briefs, scales of justice. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'judge', title: 'Judge 🔨', emoji: '🔨', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme73/400/500', prompt: 'Transform the person into a professional Judge. Attire: Judicial robe (black or red). Setting: Courtroom bench with flags. Props: Gavel, legal documents. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'police_officer', title: 'Police Officer 👮', emoji: '👮', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme74/400/500', prompt: 'Transform the person into a professional Police Officer. Attire: Police uniform with badge and cap. Setting: Police station or patrol car background. Props: Badge, radio. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'politician', title: 'Politician 🏛️', emoji: '🏛️', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme75/400/500', prompt: 'Transform the person into a professional Politician. Attire: Formal suit or traditional political attire. Setting: Parliament podium or government building. Props: Microphone, national flag. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'diplomat', title: 'Diplomat 🌍', emoji: '🌍', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme76/400/500', prompt: 'Transform the person into a professional Diplomat. Attire: Formal diplomatic attire. Setting: Embassy reception room with flags. Props: Diplomatic briefcase, formal documents. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'army_officer', title: 'Army Officer 🎖️', emoji: '🎖️', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme77/400/500', prompt: 'Transform the person into a professional Army Officer. Attire: Military dress uniform with medals and rank insignia. Setting: Military base with flag. Props: Officer\'s cap, ceremonial sword. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'ips_officer', title: 'IPS / Federal Officer 🚔', emoji: '🚔', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme78/400/500', prompt: 'Transform the person into a professional IPS/Federal Officer. Attire: Official khaki or navy uniform with stars and badge. Setting: Official government office. Props: Service cap, rank badge. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'public_prosecutor', title: 'Public Prosecutor 📜', emoji: '📜', type: 'career', category: 'Law & Government', bgImage: 'https://picsum.photos/seed/theme79/400/500', prompt: 'Transform the person into a professional Public Prosecutor. Attire: Legal gown and collar. Setting: Courthouse steps or courtroom. Props: Case files, legal documents. Maintain the person\'s facial features and likeness accurately.' },

  // Business & Finance
  { id: 'ceo', title: 'CEO / Executive 👔', emoji: '👔', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme80/400/500', prompt: 'Transform the person into a professional CEO/Executive. Attire: Sharp tailored suit. Setting: Corner office or boardroom with city view. Props: Tablet, business documents. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'investment_banker', title: 'Investment Banker 💹', emoji: '💹', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme81/400/500', prompt: 'Transform the person into a professional Investment Banker. Attire: Business formal suit. Setting: Trading floor with stock market screens. Props: Financial reports, tablet. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'chartered_accountant', title: 'Chartered Accountant 🧾', emoji: '🧾', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme82/400/500', prompt: 'Transform the person into a professional Chartered Accountant. Attire: Formal suit with CA designation badge. Setting: Professional office desk with reports. Props: Financial documents, calculator. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'entrepreneur', title: 'Entrepreneur 🚀', emoji: '🚀', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme83/400/500', prompt: 'Transform the person into a professional Entrepreneur. Attire: Smart casual in startup environment. Setting: Modern co-working space or startup office. Props: Laptop, whiteboard with business plans. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'financial_analyst', title: 'Financial Analyst 📈', emoji: '📈', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme84/400/500', prompt: 'Transform the person into a professional Financial Analyst. Attire: Business casual. Setting: Office with financial charts on screens. Props: Multiple monitors with stock charts, reports. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'marketing_manager', title: 'Marketing Manager 📣', emoji: '📣', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme85/400/500', prompt: 'Transform the person into a professional Marketing Manager. Attire: Creative business casual. Setting: Agency or office with campaign boards. Props: Tablet with marketing analytics, creative materials. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'hr_manager', title: 'HR Manager 🤝', emoji: '🤝', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme86/400/500', prompt: 'Transform the person into a professional HR Manager. Attire: Professional business attire. Setting: Modern meeting room or HR office. Props: Employee files, laptop. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'supply_chain', title: 'Supply Chain Manager 📦', emoji: '📦', type: 'career', category: 'Business & Finance', bgImage: 'https://picsum.photos/seed/theme87/400/500', prompt: 'Transform the person into a professional Supply Chain Manager. Attire: Business casual. Setting: Warehouse or logistics operations centre. Props: Tablet with inventory system, clipboard. Maintain the person\'s facial features and likeness accurately.' },

  // Education & Research
  { id: 'professor', title: 'University Professor 🎓', emoji: '🎓', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme88/400/500', prompt: 'Transform the person into a University Professor. Attire: Academic gown and mortarboard or formal attire. Setting: Lecture hall with chalkboard. Props: Academic books, lecture notes. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'school_teacher', title: 'School Teacher 📚', emoji: '📚', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme89/400/500', prompt: 'Transform the person into a School Teacher. Attire: Smart casual professional. Setting: Bright classroom with chalkboard or whiteboard. Props: Textbooks, marker. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'researcher', title: 'Research Scientist 🔬', emoji: '🔬', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme90/400/500', prompt: 'Transform the person into a Research Scientist. Attire: White lab coat with safety glasses. Setting: Research laboratory with scientific equipment. Props: Test tubes, microscope. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'archaeologist', title: 'Archaeologist 🏺', emoji: '🏺', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme91/400/500', prompt: 'Transform the person into an Archaeologist. Attire: Field gear with hat and explorer clothing. Setting: Archaeological excavation site. Props: Brush, artifact, field notebook. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'librarian', title: 'Librarian 📖', emoji: '📖', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme92/400/500', prompt: 'Transform the person into a Librarian. Attire: Formal professional attire. Setting: Large library surrounded by tall bookshelves. Props: Books, reading glasses. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'school_principal', title: 'School Principal 🏫', emoji: '🏫', type: 'career', category: 'Education & Research', bgImage: 'https://picsum.photos/seed/theme93/400/500', prompt: 'Transform the person into a School Principal. Attire: Formal suit or traditional saree/attire. Setting: Principal\'s office with trophies and certificates. Props: School crest, documents. Maintain the person\'s facial features and likeness accurately.' },

  // Aviation & Defence
  { id: 'pilot', title: 'Commercial Pilot ✈️', emoji: '✈️', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme94/400/500', prompt: 'Transform the person into a Commercial Pilot. Attire: Airline pilot uniform with four-bar epaulettes and cap. Setting: Aircraft cockpit background. Props: Pilot headset, controls. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'fighter_pilot', title: 'Fighter Pilot 🛩️', emoji: '🛩️', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme95/400/500', prompt: 'Transform the person into a Fighter Pilot. Attire: Flight suit with G-suit, helmet in hand. Setting: Jet fighter on tarmac. Props: Flight helmet, oxygen mask. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'navy_officer', title: 'Navy Officer ⚓', emoji: '⚓', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme96/400/500', prompt: 'Transform the person into a Navy Officer. Attire: Naval white dress uniform with rank insignia. Setting: Ship bridge or naval vessel. Props: Captain\'s hat, binoculars. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'air_force', title: 'Air Force Officer 🪂', emoji: '🪂', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme97/400/500', prompt: 'Transform the person into an Air Force Officer. Attire: Air force dress uniform with wings badge. Setting: Airbase with aircraft in background. Props: Service cap, medals. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'coast_guard', title: 'Coast Guard 🌊', emoji: '🌊', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme98/400/500', prompt: 'Transform the person into a Coast Guard officer. Attire: Coast guard uniform with life vest. Setting: Patrol vessel at sea. Props: Radio, binoculars. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'astronaut', title: 'Astronaut 🚀', emoji: '🚀', type: 'career', category: 'Aviation & Defence', bgImage: 'https://picsum.photos/seed/theme99/400/500', prompt: 'Transform the person into an Astronaut. Attire: NASA or ISRO spacesuit. Setting: Launch pad or space station. Props: Helmet, mission patch. Maintain the person\'s facial features and likeness accurately.' },

  // Creative & Media
  { id: 'architect', title: 'Architect 🏛️', emoji: '🏛️', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme100/400/500', prompt: 'Transform the person into a professional Architect. Attire: Formal casual. Setting: Architectural studio with blueprints and building models. Props: Blueprints, architectural model. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'fashion_designer', title: 'Fashion Designer 👗', emoji: '👗', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme101/400/500', prompt: 'Transform the person into a Fashion Designer. Attire: Stylish avant-garde outfit. Setting: Fashion design studio with mannequins and fabric. Props: Sketchbook, measuring tape. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'photographer', title: 'Photographer 📷', emoji: '📷', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme102/400/500', prompt: 'Transform the person into a professional Photographer. Attire: Casual creative wear. Setting: Photography studio with lighting equipment. Props: Professional camera with large lens. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'journalist', title: 'Journalist 🎙️', emoji: '🎙️', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme103/400/500', prompt: 'Transform the person into a Journalist. Attire: Smart casual with press badge. Setting: Newsroom or broadcast studio. Props: Microphone, press card, notepad. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'film_director', title: 'Film Director 🎬', emoji: '🎬', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme104/400/500', prompt: 'Transform the person into a Film Director. Attire: Casual director look. Setting: Movie set with director\'s chair and clapperboard. Props: Director\'s megaphone, clapperboard. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'graphic_designer', title: 'Graphic Designer 🎨', emoji: '🎨', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme105/400/500', prompt: 'Transform the person into a Graphic Designer. Attire: Creative casual. Setting: Digital art studio with large monitor showing design work. Props: Drawing tablet, stylus. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'music_producer', title: 'Music Producer 🎧', emoji: '🎧', type: 'career', category: 'Creative & Media', bgImage: 'https://picsum.photos/seed/theme106/400/500', prompt: 'Transform the person into a Music Producer. Attire: Studio casual with headphones. Setting: Professional recording studio with mixing board. Props: Headphones, mixing console. Maintain the person\'s facial features and likeness accurately.' },

  // Sports & Fitness
  { id: 'cricket_player', title: 'Cricket Player 🏏', emoji: '🏏', type: 'career', category: 'Sports & Fitness', bgImage: 'https://picsum.photos/seed/theme107/400/500', prompt: 'Transform the person into a Cricket Player. Attire: Cricket whites or coloured jersey with pads and helmet. Setting: Cricket stadium with crowd. Props: Cricket bat, helmet. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'football_player', title: 'Football Player ⚽', emoji: '⚽', type: 'career', category: 'Sports & Fitness', bgImage: 'https://picsum.photos/seed/theme108/400/500', prompt: 'Transform the person into a Football Player. Attire: Football kit with jersey and shorts. Setting: Football pitch with stadium crowd. Props: Football. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'athlete', title: 'Olympic Athlete 🏅', emoji: '🏅', type: 'career', category: 'Sports & Fitness', bgImage: 'https://picsum.photos/seed/theme109/400/500', prompt: 'Transform the person into an Olympic Athlete. Attire: Athletic gear with national colours. Setting: Olympic stadium track with flags. Props: Gold medal, national flag. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'coach', title: 'Sports Coach 🥇', emoji: '🥇', type: 'career', category: 'Sports & Fitness', bgImage: 'https://picsum.photos/seed/theme110/400/500', prompt: 'Transform the person into a Sports Coach. Attire: Team tracksuit or coaching attire. Setting: Training ground or sports facility. Props: Clipboard with tactics, whistle. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'personal_trainer', title: 'Personal Trainer 💪', emoji: '💪', type: 'career', category: 'Sports & Fitness', bgImage: 'https://picsum.photos/seed/theme111/400/500', prompt: 'Transform the person into a Personal Trainer. Attire: Athletic gym wear. Setting: Modern fitness studio or gym. Props: Dumbbells, fitness equipment. Maintain the person\'s facial features and likeness accurately.' },

  // Hospitality & Tourism
  { id: 'chef', title: 'Executive Chef 👨‍🍳', emoji: '👨‍🍳', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme112/400/500', prompt: 'Transform the person into an Executive Chef. Attire: White chef coat, chef hat, and apron. Setting: Professional restaurant kitchen with stainless steel appliances. Props: Chef knife, gourmet dish. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'hotel_manager', title: 'Hotel Manager 🏨', emoji: '🏨', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme113/400/500', prompt: 'Transform the person into a Hotel Manager. Attire: Sharp formal suit with name badge. Setting: Luxury hotel lobby with chandeliers. Props: Hotel keycard, clipboard. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'travel_agent', title: 'Travel Agent ✈️', emoji: '✈️', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme114/400/500', prompt: 'Transform the person into a Travel Agent. Attire: Smart business casual. Setting: Travel agency with world maps and destination posters. Props: Passport, travel brochures. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'tour_guide', title: 'Tour Guide 🗺️', emoji: '🗺️', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme115/400/500', prompt: 'Transform the person into a Tour Guide. Attire: Casual explorer outfit with branded vest. Setting: Famous landmark or historical site. Props: Map, flag, tour umbrella. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'bartender', title: 'Bartender 🍹', emoji: '🍹', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme116/400/500', prompt: 'Transform the person into a Bartender. Attire: Black vest, bow tie, and apron. Setting: Stylish cocktail bar with backlit shelves of bottles. Props: Cocktail shaker, glass. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'event_planner', title: 'Event Planner 🎪', emoji: '🎪', type: 'career', category: 'Hospitality & Tourism', bgImage: 'https://picsum.photos/seed/theme117/400/500', prompt: 'Transform the person into an Event Planner. Attire: Stylish professional outfit. Setting: Elegant decorated event hall. Props: Clipboard, flowers, event decorations. Maintain the person\'s facial features and likeness accurately.' },

  // Science & Research
  { id: 'physicist', title: 'Physicist ⚛️', emoji: '⚛️', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme118/400/500', prompt: 'Transform the person into a Physicist. Attire: Lab coat. Setting: Physics laboratory with particle accelerator diagrams and equations on a chalkboard. Props: Scientific instruments, equations. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'chemist', title: 'Chemist 🧪', emoji: '🧪', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme119/400/500', prompt: 'Transform the person into a Chemist. Attire: White lab coat and safety goggles. Setting: Chemistry laboratory with colorful chemical flasks and equipment. Props: Test tubes, Bunsen burner. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'biologist', title: 'Marine Biologist 🌊', emoji: '🌊', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme120/400/500', prompt: 'Transform the person into a Marine Biologist. Attire: Wetsuit or field research gear. Setting: Ocean coastline or underwater research lab. Props: Diving equipment, specimen jars. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'astronomer', title: 'Astronomer 🔭', emoji: '🔭', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme121/400/500', prompt: 'Transform the person into an Astronomer. Attire: Casual academic wear. Setting: Observatory with large telescope, starry night sky visible. Props: Telescope, star charts. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'geologist', title: 'Geologist 🪨', emoji: '🪨', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme122/400/500', prompt: 'Transform the person into a Geologist. Attire: Field gear with hat and boots. Setting: Rocky mountain terrain or canyon landscape. Props: Rock hammer, geological samples. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'environmental_scientist', title: 'Environmental Scientist 🌿', emoji: '🌿', type: 'career', category: 'Science & Research', bgImage: 'https://picsum.photos/seed/theme123/400/500', prompt: 'Transform the person into an Environmental Scientist. Attire: Field research outfit. Setting: Forest or nature reserve. Props: Soil samples, measuring equipment, notebook. Maintain the person\'s facial features and likeness accurately.' },

  // Art & Culture
  { id: 'painter', title: 'Fine Artist 🖌️', emoji: '🖌️', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme124/400/500', prompt: 'Transform the person into a Fine Artist/Painter. Attire: Paint-splattered smock. Setting: Art studio with easel and canvases. Props: Paintbrushes, palette with vibrant colors. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'sculptor', title: 'Sculptor 🗿', emoji: '🗿', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme125/400/500', prompt: 'Transform the person into a Sculptor. Attire: Casual work clothes with apron. Setting: Sculpture studio surrounded by clay and marble works. Props: Chisel, mallet, clay sculpture. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'art_curator', title: 'Art Curator 🖼️', emoji: '🖼️', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme126/400/500', prompt: 'Transform the person into an Art Curator. Attire: Elegant professional attire. Setting: Modern art museum gallery with artworks on walls. Props: Artwork catalogue, white gloves. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'interior_designer', title: 'Interior Designer 🏠', emoji: '🏠', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme127/400/500', prompt: 'Transform the person into an Interior Designer. Attire: Stylish creative outfit. Setting: Beautifully designed modern living space. Props: Design samples, mood board, tablet. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'actor', title: 'Actor / Actress 🎭', emoji: '🎭', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme128/400/500', prompt: 'Transform the person into a professional Actor. Attire: Glamorous stage or red carpet outfit. Setting: Theatre stage with spotlights or film set. Props: Script, director clapper. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'dancer', title: 'Professional Dancer 💃', emoji: '💃', type: 'career', category: 'Art & Culture', bgImage: 'https://picsum.photos/seed/theme129/400/500', prompt: 'Transform the person into a Professional Dancer. Attire: Elegant performance costume. Setting: Grand performance stage with dramatic lighting. Props: Dance pose mid-performance. Maintain the person\'s facial features and likeness accurately.' },

  // Social Services
  { id: 'social_worker', title: 'Social Worker 🤲', emoji: '🤲', type: 'career', category: 'Social Services', bgImage: 'https://picsum.photos/seed/theme130/400/500', prompt: 'Transform the person into a Social Worker. Attire: Professional casual attire with ID badge. Setting: Community centre or office. Props: Clipboard, documents, caring expression. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'psychologist', title: 'Psychologist 🧠', emoji: '🧠', type: 'career', category: 'Social Services', bgImage: 'https://picsum.photos/seed/theme131/400/500', prompt: 'Transform the person into a Psychologist. Attire: Smart professional attire. Setting: Calm therapy office with couch and soft lighting. Props: Notepad, pen, certificates on wall. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'ngo_worker', title: 'NGO / Aid Worker 🌍', emoji: '🌍', type: 'career', category: 'Social Services', bgImage: 'https://picsum.photos/seed/theme132/400/500', prompt: 'Transform the person into an NGO Aid Worker. Attire: Field vest with organization logo, practical clothing. Setting: Field location in developing region. Props: Aid supplies, clipboard. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'firefighter', title: 'Firefighter 🔥', emoji: '🔥', type: 'career', category: 'Social Services', bgImage: 'https://picsum.photos/seed/theme133/400/500', prompt: 'Transform the person into a Firefighter. Attire: Full firefighter turnout gear with helmet and oxygen tank. Setting: Fire station or dramatic fire scene background. Props: Fire hose, helmet. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'rescue_diver', title: 'Rescue Diver 🤿', emoji: '🤿', type: 'career', category: 'Social Services', bgImage: 'https://picsum.photos/seed/theme134/400/500', prompt: 'Transform the person into a Rescue Diver. Attire: Wetsuit with rescue diver gear and oxygen tank. Setting: Ocean or underwater rescue environment. Props: Diving mask, oxygen tank. Maintain the person\'s facial features and likeness accurately.' },

  // Government & Public Services
  { id: 'customs_officer', title: 'Customs Officer 🛂', emoji: '🛂', type: 'career', category: 'Government & Public Services', bgImage: 'https://picsum.photos/seed/theme135/400/500', prompt: 'Transform the person into a Customs Officer. Attire: Official customs uniform with badge. Setting: Airport or border customs checkpoint. Props: Stamp, inspection documents. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'tax_officer', title: 'Tax Officer 💰', emoji: '💰', type: 'career', category: 'Government & Public Services', bgImage: 'https://picsum.photos/seed/theme136/400/500', prompt: 'Transform the person into a Tax Officer. Attire: Formal government uniform or suit. Setting: Government tax office. Props: Documents, official seal. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'civil_servant', title: 'IAS / Civil Servant 🏛️', emoji: '🏛️', type: 'career', category: 'Government & Public Services', bgImage: 'https://picsum.photos/seed/theme137/400/500', prompt: 'Transform the person into an IAS Civil Servant. Attire: Formal government attire with official badge. Setting: Government secretariat office. Props: Official files, national emblem in background. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'air_traffic_controller', title: 'Air Traffic Controller 🛫', emoji: '🛫', type: 'career', category: 'Government & Public Services', bgImage: 'https://picsum.photos/seed/theme138/400/500', prompt: 'Transform the person into an Air Traffic Controller. Attire: Official ATC uniform with headset. Setting: Airport control tower with radar screens and runway view. Props: Headset, radar display. Maintain the person\'s facial features and likeness accurately.' },

  // Digital & Gaming
  { id: 'game_developer', title: 'Game Developer 🎮', emoji: '🎮', type: 'career', category: 'Digital & Gaming', bgImage: 'https://picsum.photos/seed/theme139/400/500', prompt: 'Transform the person into a Game Developer. Attire: Casual gaming/tech wear. Setting: Gaming studio with multiple monitors showing game development software. Props: Gaming mouse, concept art. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'esports_player', title: 'Esports Champion 🏆', emoji: '🏆', type: 'career', category: 'Digital & Gaming', bgImage: 'https://picsum.photos/seed/theme140/400/500', prompt: 'Transform the person into an Esports Champion. Attire: Team jersey with gaming headset. Setting: Esports arena with dramatic lighting and large screens. Props: Gaming setup, trophy. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'content_creator', title: 'Content Creator 📱', emoji: '📱', type: 'career', category: 'Digital & Gaming', bgImage: 'https://picsum.photos/seed/theme141/400/500', prompt: 'Transform the person into a Content Creator/YouTuber. Attire: Trendy casual outfit. Setting: Professional content creation studio with ring light and camera setup. Props: Camera, ring light, microphone. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'ui_ux_designer', title: 'UI/UX Designer 🖥️', emoji: '🖥️', type: 'career', category: 'Digital & Gaming', bgImage: 'https://picsum.photos/seed/theme142/400/500', prompt: 'Transform the person into a UI/UX Designer. Attire: Creative casual. Setting: Design studio with large screens showing app wireframes. Props: Stylus, tablet, design mockups. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'blockchain_developer', title: 'Blockchain Developer 🔗', emoji: '🔗', type: 'career', category: 'Digital & Gaming', bgImage: 'https://picsum.photos/seed/theme143/400/500', prompt: 'Transform the person into a Blockchain Developer. Attire: Smart casual tech wear. Setting: Futuristic tech office with crypto charts on screens. Props: Laptop with blockchain visualizations. Maintain the person\'s facial features and likeness accurately.' },

  // Agriculture & Environment
  { id: 'farmer', title: 'Farmer 🌾', emoji: '🌾', type: 'career', category: 'Agriculture & Environment', bgImage: 'https://picsum.photos/seed/theme144/400/500', prompt: 'Transform the person into a Farmer. Attire: Traditional farming attire with hat. Setting: Lush green farmland or paddy fields at golden hour. Props: Farming tools, crop harvest. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'agricultural_scientist', title: 'Agricultural Scientist 🌱', emoji: '🌱', type: 'career', category: 'Agriculture & Environment', bgImage: 'https://picsum.photos/seed/theme145/400/500', prompt: 'Transform the person into an Agricultural Scientist. Attire: Field research attire with lab coat. Setting: Research farm or greenhouse. Props: Plant samples, scientific notebook. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'botanist', title: 'Botanist 🌺', emoji: '🌺', type: 'career', category: 'Agriculture & Environment', bgImage: 'https://picsum.photos/seed/theme146/400/500', prompt: 'Transform the person into a Botanist. Attire: Field research clothing. Setting: Tropical botanical garden or greenhouse with exotic plants. Props: Plant specimens, magnifying glass. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'wildlife_conservationist', title: 'Wildlife Conservationist 🦁', emoji: '🦁', type: 'career', category: 'Agriculture & Environment', bgImage: 'https://picsum.photos/seed/theme147/400/500', prompt: 'Transform the person into a Wildlife Conservationist. Attire: Field safari gear. Setting: African savannah or national park. Props: Binoculars, field notebook, camera. Maintain the person\'s facial features and likeness accurately.' },

  // Healthcare Specialists
  { id: 'cardiologist', title: 'Cardiologist ❤️', emoji: '❤️', type: 'career', category: 'Healthcare Specialists', bgImage: 'https://picsum.photos/seed/theme148/400/500', prompt: 'Transform the person into a Cardiologist. Attire: White coat with stethoscope. Setting: Modern cardiology unit with ECG monitors. Props: ECG readout, stethoscope. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'neurologist', title: 'Neurologist 🧠', emoji: '🧠', type: 'career', category: 'Healthcare Specialists', bgImage: 'https://picsum.photos/seed/theme149/400/500', prompt: 'Transform the person into a Neurologist. Attire: White coat with professional attire. Setting: Neurology lab with brain scan images. Props: Brain MRI scans, medical instruments. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'optometrist', title: 'Optometrist 👁️', emoji: '👁️', type: 'career', category: 'Healthcare Specialists', bgImage: 'https://picsum.photos/seed/theme150/400/500', prompt: 'Transform the person into an Optometrist. Attire: White coat or professional attire. Setting: Eye clinic with examination equipment. Props: Eye chart, optometry instruments. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'orthopedic', title: 'Orthopedic Surgeon 🦴', emoji: '🦴', type: 'career', category: 'Healthcare Specialists', bgImage: 'https://picsum.photos/seed/theme151/400/500', prompt: 'Transform the person into an Orthopedic Surgeon. Attire: Surgical scrubs. Setting: Orthopedic operating theatre. Props: X-ray bone scan, surgical instruments. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'dermatologist', title: 'Dermatologist 💆', emoji: '💆', type: 'career', category: 'Healthcare Specialists', bgImage: 'https://picsum.photos/seed/theme152/400/500', prompt: 'Transform the person into a Dermatologist. Attire: White coat. Setting: Modern dermatology clinic. Props: Dermatoscope, skin care products. Maintain the person\'s facial features and likeness accurately.' },

  // Real Estate & Construction
  { id: 'real_estate_agent', title: 'Real Estate Agent 🏘️', emoji: '🏘️', type: 'career', category: 'Real Estate & Construction', bgImage: 'https://picsum.photos/seed/theme153/400/500', prompt: 'Transform the person into a Real Estate Agent. Attire: Sharp professional suit. Setting: Modern luxury property or real estate office. Props: Property brochure, house keys. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'urban_planner', title: 'Urban Planner 🏙️', emoji: '🏙️', type: 'career', category: 'Real Estate & Construction', bgImage: 'https://picsum.photos/seed/theme154/400/500', prompt: 'Transform the person into an Urban Planner. Attire: Business casual. Setting: City planning office with urban development maps. Props: City blueprint, scale model. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'quantity_surveyor', title: 'Quantity Surveyor 📐', emoji: '📐', type: 'career', category: 'Real Estate & Construction', bgImage: 'https://picsum.photos/seed/theme155/400/500', prompt: 'Transform the person into a Quantity Surveyor. Attire: Business casual with hard hat on site. Setting: Construction site or office with building plans. Props: Measuring tools, cost estimate documents. Maintain the person\'s facial features and likeness accurately.' },

  // Transportation & Logistics
  { id: 'ship_captain', title: 'Ship Captain ⚓', emoji: '⚓', type: 'career', category: 'Transportation & Logistics', bgImage: 'https://picsum.photos/seed/theme156/400/500', prompt: 'Transform the person into a Ship Captain. Attire: Naval captain uniform with gold-braided cap. Setting: Bridge of a large cargo or cruise ship at sea. Props: Binoculars, navigation charts. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'train_driver', title: 'Train Driver 🚂', emoji: '🚂', type: 'career', category: 'Transportation & Logistics', bgImage: 'https://picsum.photos/seed/theme157/400/500', prompt: 'Transform the person into a Train Driver. Attire: Official train driver uniform with cap. Setting: Train cabin cockpit with railway tracks ahead. Props: Train controls, radio. Maintain the person\'s facial features and likeness accurately.' },
  { id: 'logistics_manager', title: 'Logistics Manager 🚛', emoji: '🚛', type: 'career', category: 'Transportation & Logistics', bgImage: 'https://picsum.photos/seed/theme158/400/500', prompt: 'Transform the person into a Logistics Manager. Attire: Business casual with safety vest. Setting: Large logistics hub or port with containers. Props: Tablet with tracking system, clipboard. Maintain the person\'s facial features and likeness accurately.' },
];
