import { Theme } from '@/types';

export const funThemes: Theme[] = [
  // Historical & Fantasy
  { id: 'knight', title: 'Medieval Knight', emoji: '⚔️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme1/400/500', prompt: 'Transform the person into a medieval knight wearing full plate armor with a sword and shield, in a castle setting.' },
  { id: 'viking', title: 'Viking Warrior', emoji: '🪓', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme2/400/500', prompt: 'Transform the person into a Viking warrior with fur-lined armor, horned helmet, and battle axe, standing on a Norse longship.' },
  { id: 'cyberpunk', title: 'Cyberpunk Hero', emoji: '🌃', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme3/400/500', prompt: 'Transform the person into a cyberpunk hero with neon-lit augmentations, futuristic jacket, in a rain-soaked neon city at night.' },
  { id: 'elf', title: 'Elven Royalty', emoji: '🌿', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme4/400/500', prompt: 'Transform the person into elven royalty with pointed ears, flowing robes, a crown of leaves, in an enchanted forest setting.' },
  { id: 'steampunk', title: 'Steampunk Explorer', emoji: '⚙️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme5/400/500', prompt: 'Transform the person into a steampunk explorer with goggles, gears, a top hat, and a brass airship in the background.' },
  { id: 'royal', title: 'Fairytale Royal', emoji: '👑', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme6/400/500', prompt: 'Transform the person into a fairytale royal wearing an ornate crown and regal gown or suit in a grand castle ballroom.' },
  { id: 'pharaoh', title: 'Egyptian Pharaoh', emoji: '🏺', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme7/400/500', prompt: 'Transform the person into an Egyptian Pharaoh with golden headdress, kohl-lined eyes, and hieroglyphic throne room background.' },
  { id: 'renaissance', title: 'Renaissance Noble', emoji: '🎨', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme8/400/500', prompt: 'Transform the person into a Renaissance noble wearing elaborate period clothing in an Italian palazzo setting.' },
  { id: 'samurai', title: 'Samurai Warrior', emoji: '⚔️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme9/400/500', prompt: 'Transform the person into a samurai warrior in full armor with katana, cherry blossom trees in the background.' },
  { id: 'pirate', title: 'Pirate Captain', emoji: '🏴‍☠️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme10/400/500', prompt: 'Transform the person into a swashbuckling pirate captain with a tricorn hat, eyepatch, and treasure ship background.' },
  { id: 'gladiator', title: 'Roman Gladiator', emoji: '🛡️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme11/400/500', prompt: 'Transform the person into a Roman gladiator with a helmet, shield, and sword, standing in a Colosseum arena.' },
  { id: 'outlaw', title: 'Wild West Outlaw', emoji: '🤠', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme12/400/500', prompt: 'Transform the person into a Wild West outlaw with a cowboy hat, duster coat, and revolver in a dusty frontier town.' },
  { id: 'spartan', title: 'Spartan Warrior', emoji: '⚡', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme13/400/500', prompt: 'Transform the person into a Spartan warrior with a red cape, bronze helmet, and spear against ancient Greek mountains.' },
  { id: 'aztec', title: 'Aztec Priest', emoji: '🗿', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme14/400/500', prompt: 'Transform the person into an Aztec high priest with feathered headdress, ritual jewelry, at a grand Mesoamerican temple.' },
  { id: 'colonial_soldier', title: 'Colonial Soldier', emoji: '🎖️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme15/400/500', prompt: 'Transform the person into an 18th-century colonial soldier in red or blue uniform with musket, colonial village backdrop.' },
  { id: 'geisha', title: 'Geisha Artist', emoji: '🎎', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme16/400/500', prompt: 'Transform the person into a traditional Japanese geisha with white makeup, elaborate kimono, and a tea house setting.' },
  { id: 'mongol_khan', title: 'Mongol Khan', emoji: '🏹', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme17/400/500', prompt: 'Transform the person into a Mongol Khan in traditional nomadic armor on horseback across the open steppe.' },
  { id: 'celtic', title: 'Celtic Warrior', emoji: '☘️', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme18/400/500', prompt: 'Transform the person into a Celtic warrior with blue woad war paint, plaid cloak, and a misty highland battlefield.' },
  { id: 'tribal', title: 'African Tribal Leader', emoji: '🦁', type: 'fun', category: 'Historical & Fantasy', bgImage: 'https://picsum.photos/seed/theme19/400/500', prompt: 'Transform the person into an African tribal leader with elaborate traditional attire, beaded jewelry, and African savannah backdrop.' },

  // Sci-Fi & Futuristic
  { id: 'comic_hero', title: 'Comic Book Hero', emoji: '💥', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme20/400/500', prompt: 'Transform the person into a comic book superhero with a colorful costume, dynamic pose, and comic-style cityscape background.' },
  { id: 'cosmic_guardian', title: 'Cosmic Guardian', emoji: '🌌', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme21/400/500', prompt: 'Transform the person into a cosmic guardian in a glowing celestial armor among stars and nebulae in deep space.' },
  { id: 'sorcerer', title: 'Mystic Sorcerer', emoji: '✨', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme22/400/500', prompt: 'Transform the person into a mystic sorcerer with flowing robes, a magical staff with glowing orb, surrounded by arcane symbols.' },
  { id: 'dragon_slayer', title: 'Dragon Slayer', emoji: '🐉', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme23/400/500', prompt: 'Transform the person into a dragon slayer in battle-worn armor standing before a defeated dragon in a volcanic landscape.' },
  { id: 'space_explorer', title: 'Space Explorer', emoji: '🚀', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme24/400/500', prompt: 'Transform the person into a space explorer in a futuristic spacesuit on the surface of an alien planet with two moons.' },
  { id: 'cyborg', title: 'Robot Cyborg', emoji: '🤖', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme25/400/500', prompt: 'Transform the person into a half-human cyborg with mechanical limbs and glowing circuits in a futuristic laboratory.' },
  { id: 'alien_ambassador', title: 'Alien Ambassador', emoji: '👽', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme26/400/500', prompt: 'Transform the person into an alien ambassador with otherworldly features and intergalactic diplomatic attire on a starship bridge.' },
  { id: 'time_traveler', title: 'Time Traveler', emoji: '⏰', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme27/400/500', prompt: 'Transform the person into a time traveler with a vintage yet futuristic outfit surrounded by swirling time portals and clockwork gears.' },
  { id: 'mech_pilot', title: 'Mech Pilot', emoji: '🎮', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme28/400/500', prompt: 'Transform the person into a mech pilot in a sleek pilot suit inside the cockpit of a giant battle mech robot.' },
  { id: 'hologram_star', title: 'Hologram Star', emoji: '✨', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme29/400/500', prompt: 'Transform the person into a holographic music star performing on a futuristic digital stage with light projections.' },
  { id: 'scientist', title: 'Quantum Scientist', emoji: '🔬', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme30/400/500', prompt: 'Transform the person into a quantum scientist in a lab coat surrounded by holographic equations and advanced scientific equipment.' },
  { id: 'smuggler', title: 'Galaxy Smuggler', emoji: '🌌', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme31/400/500', prompt: 'Transform the person into a galaxy smuggler with a leather jacket, blaster holster, leaning against a battered starship.' },
  { id: 'detective', title: 'Victorian Detective', emoji: '🔍', type: 'fun', category: 'Sci-Fi & Futuristic', bgImage: 'https://picsum.photos/seed/theme32/400/500', prompt: 'Transform the person into a Victorian detective with a deerstalker hat, magnifying glass, in foggy 19th century London streets.' },

  // Cultural & Artistic
  { id: 'bollywood', title: 'Bollywood Star', emoji: '💃', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme33/400/500', prompt: 'Transform the person into a Bollywood star in glamorous Indian film costume with jewellery on a colourful film set.' },
  { id: 'kpop', title: 'K-Pop Idol', emoji: '🎤', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme34/400/500', prompt: 'Transform the person into a K-Pop idol with trendy fashion, flawless makeup, on a vibrant stage with colorful lights.' },
  { id: 'flamenco', title: 'Flamenco Dancer', emoji: '💃', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme35/400/500', prompt: 'Transform the person into a flamenco dancer in a red ruffled dress with a rose in hair, mid-dance on a Spanish stage.' },
  { id: 'carnival', title: 'Carnival Royalty', emoji: '🎭', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme36/400/500', prompt: 'Transform the person into Carnival royalty with an elaborate feathered headdress and sequined costume at a Rio Carnival parade.' },
  { id: 'opera', title: 'Opera Singer', emoji: '🎵', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme37/400/500', prompt: 'Transform the person into an opera singer in dramatic period costume on an ornate opera house stage.' },
  { id: 'ballet', title: 'Ballet Prima', emoji: '🩰', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme38/400/500', prompt: 'Transform the person into a ballet prima ballerina in a white tutu en pointe on a grand stage with spotlights.' },
  { id: 'tango', title: 'Tango Master', emoji: '🌹', type: 'fun', category: 'Cultural & Artistic', bgImage: 'https://picsum.photos/seed/theme39/400/500', prompt: 'Transform the person into a tango master in elegant black attire with a red rose, dancing in a Buenos Aires milonga.' },

  // Family & Personal
  { id: 'family_tree', title: 'Family Tree', emoji: '👨‍👩‍👧‍👦', type: 'fun', category: 'Family & Personal', bgImage: 'https://picsum.photos/seed/theme40/400/500', prompt: 'Create a warm illustrated family portrait scene with the person as the central figure surrounded by a beautiful family tree design.' },
  { id: 'memory_lane', title: 'Memory Lane', emoji: '📸', type: 'fun', category: 'Family & Personal', bgImage: 'https://picsum.photos/seed/theme41/400/500', prompt: 'Transform the photo into a vintage nostalgic style as if taken decades ago with warm sepia tones and retro aesthetics.' },
  { id: 'then_and_now', title: 'Then & Now', emoji: '⏳', type: 'fun', category: 'Family & Personal', bgImage: 'https://picsum.photos/seed/theme42/400/500', prompt: 'Show the person in a split image — one side as a child in vintage style, the other as their current self.' },
  { id: 'age_30_years', title: '30 Years Older', emoji: '👴', type: 'fun', category: 'Family & Personal', bgImage: 'https://picsum.photos/seed/theme43/400/500', prompt: 'Realistically age the person by 30 years — natural grey hair, wrinkles, while maintaining their core features and expression.' },

  // Superheroes
  { id: 'superman', title: 'Superman', emoji: '🦸', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme44/400/500', prompt: 'Transform the person into Superman wearing the iconic blue and red costume with cape, flying above Metropolis skyline.' },
  { id: 'wonderwoman', title: 'Wonder Woman', emoji: '👸', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme45/400/500', prompt: 'Transform the person into Wonder Woman in the iconic armored costume with golden tiara, shield, and lasso of truth.' },
  { id: 'captainamerica', title: 'Captain America', emoji: '🛡️', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme46/400/500', prompt: 'Transform the person into Captain America in the star-spangled suit holding the iconic vibranium shield.' },
  { id: 'thor', title: 'Thor', emoji: '⚡', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme47/400/500', prompt: 'Transform the person into Thor the Asgardian god with flowing red cape, armor, and Mjolnir hammer with lightning around.' },
  { id: 'flash', title: 'The Flash', emoji: '⚡', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme48/400/500', prompt: 'Transform the person into The Flash in the red lightning bolt suit, surrounded by speed lightning effects.' },
  { id: 'aquaman', title: 'Aquaman', emoji: '🔱', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme49/400/500', prompt: 'Transform the person into Aquaman in golden armor with the iconic trident, surrounded by underwater ocean scenery.' },
  { id: 'doctorstrange', title: 'Doctor Strange', emoji: '🔮', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme50/400/500', prompt: 'Transform the person into Doctor Strange with the Cloak of Levitation, Eye of Agamotto amulet, and mystical portals.' },
  { id: 'wolverine', title: 'Wolverine', emoji: '🐺', type: 'fun', category: 'Superheroes', bgImage: 'https://picsum.photos/seed/theme51/400/500', prompt: 'Transform the person into Wolverine with adamantium claws extended, wearing the iconic yellow suit or X-Men uniform.' },
];
